iam:
    role_name: pywren_exec_role_1
    instance_profile_name: pywren-standalone
s3:
    bucket: ec2-user-pywren-899
    prefix: numpywren.jobs
    # how many days do you want object to stay alive
    lifespan: 1

redis_host: ec2-3-90-161-203.compute-1.amazonaws.com
region: us-east-1

runtime:
    bucket: wukong-dependencies
    s3_key: pywren_runtime-3.6-numpywren-mod.tar.gz
    #bucket: numpywrenpublic
    #s3_key: pywren.runtime/pywren_runtime-3.6-numpywren.tar.gz

control_plane:
    ec2_instance_type: m4.4xlarge
    #target_ami : ami-db710fa3
    target_ami: ami-759bc50a
    password: potato
    spot_price: 0.0
    port: 6379
    max_idle_time: 300
    idle_terminate_granularity: 1200
    control_plane_prefix: numpywren.control
    ec2_ssh_key : CS484_DESKTOP

logging:
    level: INFO



